name: 'my_new_project'  # <--- THIS WAS MISSING AND CAUSED THE RUNTIME ERROR
version: '1.0.0'
config-version: 2
profile: 'my_new_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  materialized: tables
  your_project_name:
    test_models:
    #For all three models
#  tenant_id not_null (from dbt_project.yml)
#  created_at not_null (from dbt_project.yml)
      +columns:
        tenant_id:
          tests:
            - not_null

        created_at:
          tests:
            - not_null
 
tests:
  +severity: warn