
name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'my_new_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    # This ensures that by default, models go to the target schema 
    # (STAGING or PROD) defined in your dbt Cloud environment
    +schema: "{{ target.schema }}" 
    
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table

tests:
  +severity: warn # Global default: warn instead of fail
