name: 'my_new_project'  # <--- THIS WAS MISSING AND CAUSED THE RUNTIME ERROR
version: '1.0.0'
config-version: 2
profile: 'my_new_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    +materialized: table
 
tests:
  +severity: warn