my_new_project:
  target: dev
  outputs:
    dev:
      account : A8977680256071-ASCENDION_PARTNER
      user : SATHYANARAYANAP
      database : DB_POC_Z
      private_key : |
        -----BEGIN PRIVATE KEY-----
        MIIEowIBAAKCAQEAmICiJfmVfYiTpA9cNBBwa+6n53Y1BmEb/eIyfLts3+fl+Hpu
        ye55WA19OSmp1GQeXiuukxT31od7KrNcXpaasCZigyJ4lG5P0uj85l3t33q/AvMk
        OgJWrl+V0/UfSMZUEcWY5tDaeULoBJMGg576UGTxYohnmHuso5DkVTwa04JLtWXs
        /XiqVrYOz+6L/tbpVfTcSs2Oulv/NY64deSAwo39kbWM1OQk4MJy0ZvCGqapO0GN
        XLxfy1qdaheAMX3K+dR4O0qkWk5wCi6XkzH2JBPztjIuHHt+0TCZ0vmtU0WR028o
        sDWP7ITLMX5i6UNIOQTi/vjqunoaQmtnfgdZhwIDAQABAoIBAAdsS3g5u9MOcNFN
        hhlqq241gaq8kDwtQeWLuxVjMht7+C+uFfJyTynADlZX9tJFxUykJ601GhMxKQed
        D2PzRLhKRgVICkJ/VBdaC+VSsR9tpBqKpzrDnmCCepKEne826CStT5H8nIXGgfCn
        D2wcsuZy42T+arx7WJ3lkZesg0nEPJhVnPhf6Rq8/mecS0A9XsbNycW23cWlh5J1
        UOT5O37/fiyToKC7CfCV7+1ZbTF4Z3omfKjRLe0K9XkwYuXIwrnIqxQbgPstQWlu
        D17l/AXcjJpV2Ft9vMNtPH7mEUjP9f632fl7xbymdrfykKTGOUdADwONq6fMhKdK
        rNV2HDECgYEAzBmMQ/CHposBNZfVReKdIZHHra1c5RZGF1ymakDnqRg8hZzBiyrL
        YU2Xo9DVVgFrzNDmIwF5s+s3vgV7XxQGk06TyHU3YcSQ9WNOWRJM7wyJBqbvmp5U
        RotQGPDnszvUnvqZ+Bs0qq3tYkl95zHcRbKrFYsPAjIxQc1PL7B1c2sCgYEAv0g2
        U1f8Sq9zRatxewhvJVMjWGKlMBmg9nQzofcvM8ZTnx0YLuWraJnB9b28v6Xckg8I
        2kgsdmkiMG822I4BNTe9fNUdmvd3dAQrdIP+9HxzxsoMRWG8oFhVrQKbWgA6omGX
        qX47iob2KAfWtJZE+rPTcQj2+PIzn36iOgoA1VUCgYEAgwRrbDl9esWEsziSadg8
        8g241p6RIWYY/Go3UcH0dDHguAyWmZWRFRdQHpKyQBGNd98pvJL34y09jTfLqI8c
        YXdxmp7UPGiIfV2QL9F1nYa4d5K2ANVeWCKZ+ki7E+12Yc+RAxnDx0T7O7rdnYn+
        UqeM97lamxhJUmpPSNfHrZ0CgYBq5N/3E2RaGFJCzNxN9Rinsx49dmL5zli1YZq5
        GHm4ZUy1znyFOLPhcIuD2NRyBS6OMPixg0PVqEsC5iOwQStLoiqyaCZzQ3ftzaa7
        JkiEOEg6/w58d3IB6Vt3o81NLnOV6xPmFDUR5PoKxNandJJ3x6aRtIDP/gn7R7lA
        1fZBQQKBgFyC7LJjro8aAJ7zDdonvBTW4Hp0ZKOxjnPFQIp7Vp0eeUZEWgxUVUl2
        0qcaGm2vmwH6VZJwSLPnVjQ8fX8y8ZtPKOm79dfOVqe7hzq9l0wXRp88K6g1Nar0
        NzGc21bpjaUH+5jJIZqZkbOpJs+qWCULOq2gFMmqKLbVUmtspcM/
        -----END PRIVATE KEY-----
      type: snowflake
      role: FR__POC__ADMIN__Z
      warehouse: WH_POC_Z_DEV_XSMALL
      schema: DBT_TEST
      threads : 1
