version: 2

models:
  - name: orders
    columns:
      - name: order_id
        data_tests:
          - not_null
          - unique

      - name: order_amount
        data_tests:
          - not_negative

      - name: status
        data_tests:
          - accepted_values:
              values: ['COMPLETED', 'CANCELLED']

      - name: tenant_id
        data_tests:
          - not_null

      - name: created_at
        data_tests:
          - not_null

  - name: payments
    columns:
      - name: payment_id
        data_tests:
          - not_null
          - unique

      - name: payment_amount
        data_tests:
          - not_negative

      - name: payment_status
        data_tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED']

  - name: customers
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique

      - name: customer_status
        data_tests:
          - accepted_values:
              values: ['ACTIVE', 'INACTIVE']

# Semantic models for DEMO
  - name: stg_enrollments
    description: "staging"
    columns:
      - name: student_id
      - name: course_id
      - name: enrollment_date
  - name: dim_students
    description: "dimension model of students and their current major"
    columns:
      - name: student_id
        data_tests:
          - unique
          - not_null
  - name: dim_date
    description: "dimension date / calender"
  - name: dim_student_enrollment
    description: "dimension for students enrollments date"
  - name: dim_course
    description: "dimension of courses"
  - name: fct_enrollments
    description: "Fact Model of Enrollments"
    columns:
      - name: student_id
        data_tests:
          - not_null  # Ensures every enrollment is tied to a student