version: 2

models:
  - name: fact_customer_revenue
    description: "Gold layer: Final customer revenue metrics."
    tests:
      # Uniqueness and not null tests for primary key
      - unique:
          column_name: customer_id
      - not_null:
          column_name: customer_id
      
      # Data quality tests
      - dbt_utils.expression_is_true:
          expression: "revenue >= 0"
          description: "Revenue should never be negative"
      
      # Custom tests for business rules
      - dbt_expectations.expect_column_values_to_be_between:
          column_name: total_revenue
          min_value: 0
          max_value: 1000000
          description: "Revenue should be within reasonable bounds"