version: 2

models:
  - name: fct_subscription_transactions
    description: "Gold layer: fact table."
    
  - name: dim_customers
    description: "Customers Dim Table"

  - name: dim_plans
    description: "Plans Dim Table"